### ISSUE TITLE
bug: EXDEV: cross-device link not permitted when moving the Kind binary

### ISSUE THREAD

**Issue by ryanzhang-oss** [engineerd/setup-kind#21] opened 2020-05-21 23:04 UTC
```
with:
    version: v0.7.0
    name: kind
    wait: 300s
    skipClusterCreation: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.11/x64
downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
chmod +x /home/runner/work/_temp/174cfcc2-60fa-4457-beaa-ccc15123e9e8
##[error]EXDEV: cross-device link not permitted, rename '/home/runner/work/_temp/174cfcc2-60fa-4457-beaa-ccc15123e9e8' -> '/home/runner/bin/kind'
```

https://github.com/crossplane/addon-oam-kubernetes-local/runs/697514545?check_suite_focus=true

**Comment by radu-matei** [comment] 2020-05-21 23:52
Thanks a lot for reporting!
I can confirm that this seems to be currently broken, I suspect because of a change in how the GitHub worker is set up.

I am actively working on this, and hope to have a release soon.
Thanks!

**Comment by radu-matei** [comment] 2020-05-22 00:39
@ryanzhang-oss - I created a new release with a fix for this - https://github.com/engineerd/setup-kind/releases/tag/v0.4.0

Thanks again for reporting!

**Closed** 2020-05-22 00:41 UTC

**Comment by ryanzhang-oss** [comment] 2020-05-22 07:12
Thank you very much for the quick turn around time, I am a fan now!
